### ISSUE TITLE
Bottom Shade of Views

### ISSUE THREAD

**Issue by kael-moreno** [chengdazhi/DecentBanner#13] opened 2016-08-31 09:37 UTC
@chengdazhi was wondering also if you can put a method that we can disable the gradient part at the bottom? My views dont need the dark part because there's no title per view, and it hides important contents of the view.

**Comment by chengdazhi** [comment] 2016-08-31 10:08
@kaelitokael Thanks for the advice. I have added a switch to DecentBanner.
To enable/disable the gradient cover, just import the new version 1.0.7 and call

``` java
decentBanner.setGradientEnabled(boolean enabled);
```

And you can query the visibility of gradient cover by calling

``` java
decentBanner.isGradientEnabled()
```

**Comment by chengdazhi** [comment] 2016-09-02 04:00
@kaelitokael please close this if the problem is solved. Thanks.

**Closed as completed** 2016-09-23 09:13 UTC
